### PR TITLE
Add Japnese Language

### PR DESCRIPTION
**Pull request by reindex-ot**
However, the translation is not perfect and will be updated as soon as the pull request is accepted and the apk is build...

### CODE REVIEW

**Comment by reindex-ot** [comment]
I think we are about 80% done.
The rest I can't figure out without looking at the UI and such, so I will continue as soon as it is merged.

**Comment by MonwF** [comment]
> I think we are about 80% done. The rest I can't figure out without looking at the UI and such, so I will continue as soon as it is merged.

thanks. i will merge util 95% of all strings are translated

**Comment by reindex-ot** [comment]
Okay, I'll do my best...

**Comment by reindex-ot** [comment]
Japanese has been fully translated.

**Comment by MonwF** [comment]
you should never rename readme.md，but create new file named readme_jp.md. i will merge later due to chinese new year.

**Comment by reindex-ot** [comment]
renamed README_jp.md
https://github.com/reindex-ot/customiuizer/blob/main/README_jp.md

**Comment by reindex-ot** [comment]
Translation omissions have been corrected and adjusted for completeness.

**Comment by MonwF** [comment]
thanks for your work

**Pull request merged**
