### PR TITLE
add Japanese Translate

### PR DESCRIPTION
**Pull request by Katsuyuki-Karasawa**
I'm halfway through, so I'll take it a bit at a time.

### CODE REVIEW

**Comment by MonwF** [comment]
thx. Please translate from lastest strings

**Comment by Katsuyuki-Karasawa** [comment]
[strings](https://github.com/MonwF/customiuizer/blob/main/app/src/main/res/values/strings.xml)
This?

**Comment by MonwF** [comment]
yes

**Comment by Katsuyuki-Karasawa** [comment]
maybe fixed

**Comment by Katsuyuki-Karasawa** [comment]
follows https://github.com/MonwF/customiuizer/pull/125

**Pull request closed without merging**
